<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ExercisesSeeder extends Seeder
{
    public function run(): void
    {
        $exercises = [

            // ---------------- PECHO ----------------
            ['name' => 'Press de banca',                  'muscle_group' => 'pecho', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press de banca inclinado',         'muscle_group' => 'pecho', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press con mancuernas',             'muscle_group' => 'pecho', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Press inclinado con mancuernas',   'muscle_group' => 'pecho', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Aperturas con mancuernas',         'muscle_group' => 'pecho', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Cruce de poleas',                  'muscle_group' => 'pecho', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press en máquina',                 'muscle_group' => 'pecho', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Flexiones de pecho',               'muscle_group' => 'pecho', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Fondos en paralelas',              'muscle_group' => 'pecho', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Press de banca declinado',          'muscle_group' => 'pecho', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press cerrado (agarre estrecho)',    'muscle_group' => 'pecho', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press declinado con mancuernas',     'muscle_group' => 'pecho', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Aperturas inclinadas con mancuernas', 'muscle_group' => 'pecho', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Pullover con mancuerna (pecho)',     'muscle_group' => 'pecho', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press en máquina inclinado',         'muscle_group' => 'pecho', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Pec deck (contractora)',             'muscle_group' => 'pecho', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Cruce de poleas bajo a alto',        'muscle_group' => 'pecho', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Cruce de poleas alto a bajo',        'muscle_group' => 'pecho', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press con banda elástica',           'muscle_group' => 'pecho', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Aperturas con banda elástica',       'muscle_group' => 'pecho', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Flexiones con manos elevadas',       'muscle_group' => 'pecho', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Flexiones con manos elevadas (pies arriba)', 'muscle_group' => 'pecho', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Flexiones diamante',                 'muscle_group' => 'pecho', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Fondos en banco',                    'muscle_group' => 'pecho', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Press Svend',                        'muscle_group' => 'pecho', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_only'],

            // ---------------- ESPALDA ----------------
            ['name' => 'Peso muerto',                      'muscle_group' => 'espalda', 'equipment' => 'barra',         'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Remo con barra',                   'muscle_group' => 'espalda', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Remo con mancuerna a una mano',    'muscle_group' => 'espalda', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Jalón al pecho',                   'muscle_group' => 'espalda', 'equipment' => 'cable_polea',   'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Remo en polea baja',               'muscle_group' => 'espalda', 'equipment' => 'cable_polea',   'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Pull-over con mancuerna',          'muscle_group' => 'espalda', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Dominadas',                        'muscle_group' => 'espalda', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Remo en máquina',                  'muscle_group' => 'espalda', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Face pull con banda',              'muscle_group' => 'espalda', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Remo en T',                        'muscle_group' => 'espalda', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Remo Pendlay',                      'muscle_group' => 'espalda', 'equipment' => 'barra',         'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Jalón tras nuca',                   'muscle_group' => 'espalda', 'equipment' => 'cable_polea',   'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Jalón con agarre cerrado',          'muscle_group' => 'espalda', 'equipment' => 'cable_polea',   'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Dominadas asistidas',               'muscle_group' => 'espalda', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Remo invertido',                    'muscle_group' => 'espalda', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Peso muerto rumano',                'muscle_group' => 'espalda', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Peso muerto sumo',                  'muscle_group' => 'espalda', 'equipment' => 'barra',         'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Peso muerto con mancuernas',        'muscle_group' => 'espalda', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Remo con cable a una mano',         'muscle_group' => 'espalda', 'equipment' => 'cable_polea',   'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Pulldown con brazos rectos',        'muscle_group' => 'espalda', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Remo Meadows',                      'muscle_group' => 'espalda', 'equipment' => 'barra',         'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Remo en máquina hammer',            'muscle_group' => 'espalda', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Hiperextensiones',                  'muscle_group' => 'espalda', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Buenos días',                       'muscle_group' => 'espalda', 'equipment' => 'barra',         'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Superman',                          'muscle_group' => 'espalda', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Remo Kroc',                         'muscle_group' => 'espalda', 'equipment' => 'mancuernas',    'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Encogimientos de trapecio con barra', 'muscle_group' => 'espalda', 'equipment' => 'barra',         'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Encogimientos con mancuernas',      'muscle_group' => 'espalda', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Dominadas con agarre supino',       'muscle_group' => 'espalda', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],

            // ---------------- HOMBROS ----------------
            ['name' => 'Press militar con barra',          'muscle_group' => 'hombros', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press Arnold',                     'muscle_group' => 'hombros', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Elevaciones laterales',            'muscle_group' => 'hombros', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Elevaciones frontales',            'muscle_group' => 'hombros', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Pájaros (deltoide posterior)',     'muscle_group' => 'hombros', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Press militar en máquina',         'muscle_group' => 'hombros', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Remo al mentón',                   'muscle_group' => 'hombros', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Pike push-up',                     'muscle_group' => 'hombros', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Press militar sentado con mancuernas', 'muscle_group' => 'hombros', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press tras nuca',                    'muscle_group' => 'hombros', 'equipment' => 'barra',         'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Elevaciones laterales en polea',     'muscle_group' => 'hombros', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Elevaciones frontales con barra',    'muscle_group' => 'hombros', 'equipment' => 'barra',         'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Elevaciones frontales con polea',    'muscle_group' => 'hombros', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Pájaros en polea',                   'muscle_group' => 'hombros', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Deltoide posterior en máquina (peck deck inverso)', 'muscle_group' => 'hombros', 'equipment' => 'maquina', 'difficulty' => 'beginner', 'metric_type' => 'reps_weight'],
            ['name' => 'Elevaciones laterales en máquina',   'muscle_group' => 'hombros', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Face pull en polea',                 'muscle_group' => 'hombros', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Encogimientos de hombros con barra', 'muscle_group' => 'hombros', 'equipment' => 'barra',         'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Encogimientos de hombros con mancuernas', 'muscle_group' => 'hombros', 'equipment' => 'mancuernas', 'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Press militar con banda elástica',   'muscle_group' => 'hombros', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Elevaciones laterales con banda elástica', 'muscle_group' => 'hombros', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner', 'metric_type' => 'reps_only'],
            ['name' => 'Circunducciones de hombro (movilidad)', 'muscle_group' => 'hombros', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Flexiones pike elevadas',            'muscle_group' => 'hombros', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Handstand push-up',                  'muscle_group' => 'hombros', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],

            // ---------------- BÍCEPS ----------------
            ['name' => 'Curl con barra',                   'muscle_group' => 'biceps', 'equipment' => 'barra',         'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl con mancuernas',               'muscle_group' => 'biceps', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl martillo',                     'muscle_group' => 'biceps', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl concentrado',                  'muscle_group' => 'biceps', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Curl en banco Scott',               'muscle_group' => 'biceps', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Curl con banda elástica',           'muscle_group' => 'biceps', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Curl en polea',                     'muscle_group' => 'biceps', 'equipment' => 'cable_polea',   'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl inclinado con mancuernas',      'muscle_group' => 'biceps', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Curl 21s',                           'muscle_group' => 'biceps', 'equipment' => 'barra',         'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl con barra Z',                   'muscle_group' => 'biceps', 'equipment' => 'barra',         'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl martillo en polea (cuerda)',    'muscle_group' => 'biceps', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Curl en máquina',                    'muscle_group' => 'biceps', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl araña (spider curl)',           'muscle_group' => 'biceps', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Curl invertido con barra',           'muscle_group' => 'biceps', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Dominadas supinas (agarre cerrado)', 'muscle_group' => 'biceps', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],

            // ---------------- TRÍCEPS ----------------
            ['name' => 'Press francés',                     'muscle_group' => 'triceps', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Extensión de tríceps con mancuerna', 'muscle_group' => 'triceps', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Patada de tríceps',                  'muscle_group' => 'triceps', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Jalón de tríceps en polea',          'muscle_group' => 'triceps', 'equipment' => 'cable_polea',   'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Press cerrado con barra',            'muscle_group' => 'triceps', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Fondos en banco',                    'muscle_group' => 'triceps', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Extensión de tríceps sobre la cabeza con mancuerna', 'muscle_group' => 'triceps', 'equipment' => 'mancuernas', 'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Extensión de tríceps en polea alta (cuerda)', 'muscle_group' => 'triceps', 'equipment' => 'cable_polea', 'difficulty' => 'beginner', 'metric_type' => 'reps_weight'],
            ['name' => 'Extensión de tríceps en polea (agarre invertido)', 'muscle_group' => 'triceps', 'equipment' => 'cable_polea', 'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press francés con mancuernas',        'muscle_group' => 'triceps', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Press de tríceps en máquina',         'muscle_group' => 'triceps', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Fondos en paralelas (enfoque tríceps)', 'muscle_group' => 'triceps', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Flexiones diamante (enfoque tríceps)', 'muscle_group' => 'triceps', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Extensión de tríceps con banda elástica', 'muscle_group' => 'triceps', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner', 'metric_type' => 'reps_only'],
            ['name' => 'Patada de tríceps en polea',           'muscle_group' => 'triceps', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],

            // ---------------- ANTEBRAZO ----------------
            ['name' => 'Curl de muñeca con barra',           'muscle_group' => 'antebrazo', 'equipment' => 'barra',      'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Farmer walk',                        'muscle_group' => 'antebrazo', 'equipment' => 'mancuernas', 'difficulty' => 'intermediate', 'metric_type' => 'distance'],
            ['name' => 'Dead hang (colgado de barra)',       'muscle_group' => 'antebrazo', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',   'metric_type' => 'duration'],
            ['name' => 'Curl de muñeca inverso con barra',    'muscle_group' => 'antebrazo', 'equipment' => 'barra',         'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl de muñeca con mancuerna',        'muscle_group' => 'antebrazo', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl de muñeca inverso con mancuerna', 'muscle_group' => 'antebrazo', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Extensión de muñeca en polea',        'muscle_group' => 'antebrazo', 'equipment' => 'cable_polea',   'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl de muñeca en polea',              'muscle_group' => 'antebrazo', 'equipment' => 'cable_polea',   'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Rotación de muñeca con mancuerna (pronación/supinación)', 'muscle_group' => 'antebrazo', 'equipment' => 'mancuernas', 'difficulty' => 'beginner', 'metric_type' => 'reps_weight'],
            ['name' => 'Plate pinch (agarre de disco)',        'muscle_group' => 'antebrazo', 'equipment' => 'maquina',       'difficulty' => 'intermediate', 'metric_type' => 'duration'],
            ['name' => 'Farmer walk con kettlebell',           'muscle_group' => 'antebrazo', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'distance'],
            ['name' => 'Dead hang con peso (lastrado)',        'muscle_group' => 'antebrazo', 'equipment' => 'mancuernas',    'difficulty' => 'advanced',     'metric_type' => 'duration'],
            ['name' => 'Colgado a una mano (single-arm hang)', 'muscle_group' => 'antebrazo', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'duration'],
            ['name' => 'Wrist roller (rodillo de muñeca)',     'muscle_group' => 'antebrazo', 'equipment' => 'maquina',       'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Exprimidor de mano (hand gripper)',    'muscle_group' => 'antebrazo', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],

            // ---------------- PIERNAS ----------------
            ['name' => 'Sentadilla con barra',               'muscle_group' => 'piernas', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Sentadilla goblet',                  'muscle_group' => 'piernas', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Prensa de piernas (leg press)',      'muscle_group' => 'piernas', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Zancadas con mancuernas',            'muscle_group' => 'piernas', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Peso muerto rumano',                 'muscle_group' => 'piernas', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Extensión de cuádriceps',            'muscle_group' => 'piernas', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Curl femoral',                       'muscle_group' => 'piernas', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Sentadilla búlgara',                 'muscle_group' => 'piernas', 'equipment' => 'mancuernas',    'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Sentadilla con salto',               'muscle_group' => 'piernas', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Sentadilla air squat',               'muscle_group' => 'piernas', 'equipment' => 'crossfit',      'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Sentadilla frontal',                  'muscle_group' => 'piernas', 'equipment' => 'barra',         'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Sentadilla hack',                     'muscle_group' => 'piernas', 'equipment' => 'maquina',       'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Zancadas caminando',                  'muscle_group' => 'piernas', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Zancadas con barra',                  'muscle_group' => 'piernas', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Peso muerto rumano con mancuernas',   'muscle_group' => 'piernas', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Curl femoral tumbado',                'muscle_group' => 'piernas', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Sissy squat',                         'muscle_group' => 'piernas', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Zancadas búlgaras en máquina Smith',  'muscle_group' => 'piernas', 'equipment' => 'maquina',       'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Sentadilla con banda elástica',       'muscle_group' => 'piernas', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Wall sit',                            'muscle_group' => 'piernas', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'duration'],
            ['name' => 'Step-up con mancuernas',              'muscle_group' => 'piernas', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Prensa a una pierna',                 'muscle_group' => 'piernas', 'equipment' => 'maquina',       'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],


            // ---------------- GLÚTEOS ----------------
            ['name' => 'Hip thrust con barra',               'muscle_group' => 'gluteos', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Patada de glúteo en polea',          'muscle_group' => 'gluteos', 'equipment' => 'cable_polea',   'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Puente de glúteo',                   'muscle_group' => 'gluteos', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Abducción de cadera en máquina',     'muscle_group' => 'gluteos', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Peso muerto sumo',                   'muscle_group' => 'gluteos', 'equipment' => 'barra',         'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Hip thrust con mancuerna',            'muscle_group' => 'gluteos', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Hip thrust en máquina',               'muscle_group' => 'gluteos', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Puente de glúteo a una pierna',       'muscle_group' => 'gluteos', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Patada de glúteo en máquina',         'muscle_group' => 'gluteos', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Abducción de cadera con banda elástica', 'muscle_group' => 'gluteos', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner', 'metric_type' => 'reps_only'],
            ['name' => 'Almeja con banda elástica (clamshell)', 'muscle_group' => 'gluteos', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner', 'metric_type' => 'reps_only'],
            ['name' => 'Buenos días con barra (enfoque glúteo)', 'muscle_group' => 'gluteos', 'equipment' => 'barra',       'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Zancada reversa (enfoque glúteo)',    'muscle_group' => 'gluteos', 'equipment' => 'mancuernas',    'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],


            // ---------------- PANTORRILLAS ----------------
            ['name' => 'Elevación de talones de pie',        'muscle_group' => 'pantorrillas', 'equipment' => 'maquina',    'difficulty' => 'beginner', 'metric_type' => 'reps_weight'],
            ['name' => 'Elevación de talones sentado',       'muscle_group' => 'pantorrillas', 'equipment' => 'maquina',    'difficulty' => 'beginner', 'metric_type' => 'reps_weight'],
            ['name' => 'Elevación de talones con mancuernas', 'muscle_group' => 'pantorrillas', 'equipment' => 'mancuernas', 'difficulty' => 'beginner', 'metric_type' => 'reps_weight'],
            ['name' => 'Elevación de talones en prensa',       'muscle_group' => 'pantorrillas', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Elevación de talones a una pierna',    'muscle_group' => 'pantorrillas', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Elevación de talones con barra',       'muscle_group' => 'pantorrillas', 'equipment' => 'barra',         'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Salto de cuerda',                      'muscle_group' => 'pantorrillas', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'duration'],
            ['name' => 'Elevación de talones burro (donkey calf raise)', 'muscle_group' => 'pantorrillas', 'equipment' => 'maquina', 'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],

            // ---------------- ABDOMEN ----------------
            ['name' => 'Plancha (plank)',                    'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'duration'],
            ['name' => 'Crunch abdominal',                   'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Elevación de piernas colgado',       'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Rueda abdominal (ab wheel)',         'muscle_group' => 'abdomen', 'equipment' => 'otro',          'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Russian twist con mancuerna',        'muscle_group' => 'abdomen', 'equipment' => 'mancuernas',    'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Hollow hold',                        'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'duration'],
            ['name' => 'Plancha lateral (side plank)',       'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'duration'],
            ['name' => 'Crunch en polea (arrodillado)',      'muscle_group' => 'abdomen', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Crunch en máquina',                  'muscle_group' => 'abdomen', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Elevación de piernas tumbado',       'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Elevación de rodillas colgado',      'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Bicicleta abdominal (bicycle crunch)', 'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Russian twist con peso',             'muscle_group' => 'abdomen', 'equipment' => 'otro',          'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Toque de talones (heel touches)',    'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'V-ups',                              'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Dead bug',                           'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Plancha con toque de hombro',        'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'duration'],
            ['name' => 'Sit-up',                             'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'Sit-up con banco declinado',         'muscle_group' => 'abdomen', 'equipment' => 'maquina',       'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Mountain climbers',                  'muscle_group' => 'abdomen', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'duration'],
            ['name' => 'Press Pallof',                       'muscle_group' => 'abdomen', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Giro ruso en polea (woodchopper)',   'muscle_group' => 'abdomen', 'equipment' => 'cable_polea',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Plancha con banda elástica',         'muscle_group' => 'abdomen', 'equipment' => 'banda_elastica', 'difficulty' => 'beginner',     'metric_type' => 'duration'],

            // ---------------- CUERPO COMPLETO / CALISTENIA ----------------
            ['name' => 'Burpees',                            'muscle_group' => 'cuerpo_completo', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Mountain climbers',                  'muscle_group' => 'cuerpo_completo', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'duration'],
            ['name' => 'Jumping jacks',                      'muscle_group' => 'cuerpo_completo', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'duration'],
            ['name' => 'Muscle-up',                          'muscle_group' => 'cuerpo_completo', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Flexiones con salto (plyo push-up)',  'muscle_group' => 'cuerpo_completo', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Bear crawl',                          'muscle_group' => 'cuerpo_completo', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'duration'],
            ['name' => 'Sprawl',                              'muscle_group' => 'cuerpo_completo', 'equipment' => 'peso_corporal', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Turkish get-up',                      'muscle_group' => 'cuerpo_completo', 'equipment' => 'kettlebell',    'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Man makers',                          'muscle_group' => 'cuerpo_completo', 'equipment' => 'mancuernas',    'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],


            // ---------------- CROSSFIT ----------------
            ['name' => 'Kettlebell swing',                   'muscle_group' => 'cuerpo_completo', 'equipment' => 'kettlebell', 'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Box jump',                            'muscle_group' => 'piernas',         'equipment' => 'crossfit',   'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'Wall balls',                          'muscle_group' => 'cuerpo_completo', 'equipment' => 'crossfit',   'difficulty' => 'intermediate', 'metric_type' => 'reps_weight'],
            ['name' => 'Thrusters',                           'muscle_group' => 'cuerpo_completo', 'equipment' => 'barra',      'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Clean and jerk',                      'muscle_group' => 'cuerpo_completo', 'equipment' => 'barra',      'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Battle ropes',                        'muscle_group' => 'cuerpo_completo', 'equipment' => 'crossfit',   'difficulty' => 'intermediate', 'metric_type' => 'duration'],
            ['name' => 'Salto de cuerda (jump rope)',         'muscle_group' => 'cardio',          'equipment' => 'crossfit',   'difficulty' => 'beginner',     'metric_type' => 'duration'],
            ['name' => 'Remo en máquina (rowing)',            'muscle_group' => 'cardio',          'equipment' => 'maquina',    'difficulty' => 'beginner',     'metric_type' => 'distance'],
            ['name' => 'Kettlebell snatch',                   'muscle_group' => 'cuerpo_completo', 'equipment' => 'kettlebell', 'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Kettlebell goblet squat',              'muscle_group' => 'piernas',         'equipment' => 'kettlebell', 'difficulty' => 'beginner',     'metric_type' => 'reps_weight'],
            ['name' => 'Snatch',                               'muscle_group' => 'cuerpo_completo', 'equipment' => 'barra',      'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Clean',                                'muscle_group' => 'cuerpo_completo', 'equipment' => 'barra',      'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Push press',                           'muscle_group' => 'hombros',         'equipment' => 'barra',      'difficulty' => 'advanced',     'metric_type' => 'reps_weight'],
            ['name' => 'Sled push',                            'muscle_group' => 'cuerpo_completo', 'equipment' => 'crossfit',   'difficulty' => 'intermediate', 'metric_type' => 'distance'],
            ['name' => 'Sled pull (arrastre de trineo)',       'muscle_group' => 'cuerpo_completo', 'equipment' => 'crossfit',   'difficulty' => 'intermediate', 'metric_type' => 'distance'],
            ['name' => 'Double unders (salto doble)',          'muscle_group' => 'cardio',          'equipment' => 'crossfit',   'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'Assault bike',                         'muscle_group' => 'cardio',          'equipment' => 'maquina',    'difficulty' => 'intermediate', 'metric_type' => 'duration'],


            // ---------------- CARDIO ----------------
            ['name' => 'Carrera en cinta',                    'muscle_group' => 'cardio', 'equipment' => 'maquina', 'difficulty' => 'beginner', 'metric_type' => 'duration'],
            ['name' => 'Bicicleta estática',                  'muscle_group' => 'cardio', 'equipment' => 'maquina', 'difficulty' => 'beginner', 'metric_type' => 'duration'],
            ['name' => 'Elíptica',                            'muscle_group' => 'cardio', 'equipment' => 'maquina', 'difficulty' => 'beginner', 'metric_type' => 'duration'],
            ['name' => 'Escaladora (stair climber)',          'muscle_group' => 'cardio', 'equipment' => 'maquina', 'difficulty' => 'intermediate', 'metric_type' => 'duration'],
            ['name' => 'Caminadora inclinada (incline walk)',  'muscle_group' => 'cardio', 'equipment' => 'maquina',       'difficulty' => 'beginner',     'metric_type' => 'duration'],
            ['name' => 'Bicicleta spinning',                   'muscle_group' => 'cardio', 'equipment' => 'maquina',       'difficulty' => 'intermediate', 'metric_type' => 'duration'],
            ['name' => 'Natación',                             'muscle_group' => 'cardio', 'equipment' => 'otro',          'difficulty' => 'intermediate', 'metric_type' => 'duration'],
            ['name' => 'Correr al aire libre',                 'muscle_group' => 'cardio', 'equipment' => 'peso_corporal', 'difficulty' => 'beginner',     'metric_type' => 'distance'],
            ['name' => 'Sprints (carrera corta intensa)',      'muscle_group' => 'cardio', 'equipment' => 'peso_corporal', 'difficulty' => 'advanced',     'metric_type' => 'distance'],
            ['name' => 'Ciclismo al aire libre',               'muscle_group' => 'cardio', 'equipment' => 'otro',          'difficulty' => 'intermediate', 'metric_type' => 'distance'],


            // ---------------- TRX ----------------
            ['name' => 'TRX rows',                            'muscle_group' => 'espalda', 'equipment' => 'trx', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'TRX chest press',                     'muscle_group' => 'pecho',   'equipment' => 'trx', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'TRX squat',                           'muscle_group' => 'piernas', 'equipment' => 'trx', 'difficulty' => 'beginner',     'metric_type' => 'reps_only'],
            ['name' => 'TRX bíceps curl',                      'muscle_group' => 'biceps',   'equipment' => 'trx', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'TRX tríceps extension',                'muscle_group' => 'triceps',  'equipment' => 'trx', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'TRX hamstring curl',                   'muscle_group' => 'piernas',  'equipment' => 'trx', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'TRX pike',                              'muscle_group' => 'abdomen',  'equipment' => 'trx', 'difficulty' => 'advanced',     'metric_type' => 'reps_only'],
            ['name' => 'TRX Y-fly (deltoide)',                  'muscle_group' => 'hombros',  'equipment' => 'trx', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
            ['name' => 'TRX lunge',                             'muscle_group' => 'piernas',  'equipment' => 'trx', 'difficulty' => 'intermediate', 'metric_type' => 'reps_only'],
        ];

        foreach ($exercises as $exercise) {
            Exercise::updateOrCreate(
                ['slug' => Str::slug($exercise['name'])],
                array_merge($exercise, [
                    'slug'      => Str::slug($exercise['name']),
                    'is_active' => true,
                ])
            );
        }
    }
}